CREATE TABLE mileages (
	id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
	techid INTEGER,
	datetime TEXT,
	mileage REAL,
	description TEXT,
	FOREIGN KEY (techid) REFERENCES techs (id)
	ON DELETE CASCADE
	ON UPDATE CASCADE
);