CREATE TABLE maintenance (
	id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
	techid INTEGER,
	mtid INTEGER,
	datetime TEXT,
	mileagecommon REAL,
	mileageaftermaintenance REAL,
	FOREIGN KEY (techid) REFERENCES techs (id)
	ON DELETE SET NULL
	ON UPDATE CASCADE,
	FOREIGN KEY (mtid) REFERENCES mts (id)
	ON DELETE SET NULL
	ON UPDATE CASCADE
);