//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Technics.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ResourcesSql {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourcesSql() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Technics.Properties.ResourcesSql", typeof(ResourcesSql).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE TABLE folders (
        ///	id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
        ///	parentid INTEGER,
        ///	text TEXT
        ///);.
        /// </summary>
        internal static string CreateTableFolders {
            get {
                return ResourceManager.GetString("CreateTableFolders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE TABLE mileages (
        ///	id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
        ///	techid INTEGER,
        ///	datetime TEXT,
        ///	mileage REAL,
        ///	description TEXT,
        ///	FOREIGN KEY (techid) REFERENCES techs (id)
        ///	ON DELETE CASCADE
        ///	ON UPDATE CASCADE
        ///);.
        /// </summary>
        internal static string CreateTableMileages {
            get {
                return ResourceManager.GetString("CreateTableMileages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE TABLE parts (
        ///	id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
        ///	text TEXT
        ///);.
        /// </summary>
        internal static string CreateTableParts {
            get {
                return ResourceManager.GetString("CreateTableParts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE TABLE techparts (
        ///	id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
        ///	techid INTEGER,
        ///	partid INTEGER,
        ///	datetimeinstall TEXT,
        ///	datetimeremove TEXT
        ///);.
        /// </summary>
        internal static string CreateTableTechParts {
            get {
                return ResourceManager.GetString("CreateTableTechParts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE TABLE techs (
        ///	id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
        ///	folderid INTEGER,
        ///	text TEXT
        ///);.
        /// </summary>
        internal static string CreateTableTechs {
            get {
                return ResourceManager.GetString("CreateTableTechs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT IFNULL(SUM(mileage), 0.0)
        ///FROM mileages
        ///WHERE techid = :techid AND datetime &lt;= :datetime;.
        /// </summary>
        internal static string GetMileageCommon {
            get {
                return ResourceManager.GetString("GetMileageCommon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT IFNULL(SUM(mileage), 0.0)
        ///FROM mileages
        ///WHERE techid = :techid AND datetime &lt; :datetime;.
        /// </summary>
        internal static string GetMileageCommonPrev {
            get {
                return ResourceManager.GetString("GetMileageCommonPrev", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT IFNULL(SUM(mileage), 0.0)
        ///FROM mileages
        ///WHERE techid = :techid AND datetime &lt;= :datetime;.
        /// </summary>
        internal static string SelectMileages {
            get {
                return ResourceManager.GetString("SelectMileages", resourceCulture);
            }
        }
    }
}
