//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Technics.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ResourcesLog {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourcesLog() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Technics.Properties.ResourcesLog", typeof(ResourcesLog).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to add tracks canceled.
        /// </summary>
        internal static string CheckDirectoryTracksCancel {
            get {
                return ResourceManager.GetString("CheckDirectoryTracksCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to directory tracks not exists.
        /// </summary>
        internal static string CheckDirectoryTracksNotExists {
            get {
                return ResourceManager.GetString("CheckDirectoryTracksNotExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to found files={0}, new files={1}.
        /// </summary>
        internal static string CheckDirectoryTracksOk {
            get {
                return ResourceManager.GetString("CheckDirectoryTracksOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to directory tracks empty.
        /// </summary>
        internal static string CheckDirectoryTracksPathEmpty {
            get {
                return ResourceManager.GetString("CheckDirectoryTracksPathEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to closed from exit call.
        /// </summary>
        internal static string CloseReasonApplicationExitCall {
            get {
                return ResourceManager.GetString("CloseReasonApplicationExitCall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to windows shutdown.
        /// </summary>
        internal static string CloseReasonShutDown {
            get {
                return ResourceManager.GetString("CloseReasonShutDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to closed from task manager.
        /// </summary>
        internal static string CloseReasonTaskManager {
            get {
                return ResourceManager.GetString("CloseReasonTaskManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to database create ok.
        /// </summary>
        internal static string DatabaseCreateOk {
            get {
                return ResourceManager.GetString("DatabaseCreateOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} items delete ok, count={1}.
        /// </summary>
        internal static string ListItemDeleteOk {
            get {
                return ResourceManager.GetString("ListItemDeleteOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} items save ok, count={1}.
        /// </summary>
        internal static string ListItemSaveOk {
            get {
                return ResourceManager.GetString("ListItemSaveOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} ok, count={1}.
        /// </summary>
        internal static string ListLoadOk {
            get {
                return ResourceManager.GetString("ListLoadOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} in {1}.
        /// </summary>
        internal static string LoadFromFileFail {
            get {
                return ResourceManager.GetString("LoadFromFileFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to wrong header in {0}.
        /// </summary>
        internal static string LoadFromFileFailWrongHeader {
            get {
                return ResourceManager.GetString("LoadFromFileFailWrongHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} ok, count={1}.
        /// </summary>
        internal static string LoadFromFileOk {
            get {
                return ResourceManager.GetString("LoadFromFileOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ok.
        /// </summary>
        internal static string LoadOk {
            get {
                return ResourceManager.GetString("LoadOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to open files in {0}, count={1}.
        /// </summary>
        internal static string OpenFiles {
            get {
                return ResourceManager.GetString("OpenFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to app directory.
        /// </summary>
        internal static string PathAppDirectory {
            get {
                return ResourceManager.GetString("PathAppDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to database.
        /// </summary>
        internal static string PathDatabase {
            get {
                return ResourceManager.GetString("PathDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to data directory.
        /// </summary>
        internal static string PathDataDirectory {
            get {
                return ResourceManager.GetString("PathDataDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to created.
        /// </summary>
        internal static string PathDataDirectoryCreateOk {
            get {
                return ResourceManager.GetString("PathDataDirectoryCreateOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to logs directory.
        /// </summary>
        internal static string PathLogsDirectory {
            get {
                return ResourceManager.GetString("PathLogsDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to settings.
        /// </summary>
        internal static string PathSettings {
            get {
                return ResourceManager.GetString("PathSettings", resourceCulture);
            }
        }
    }
}
