//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Technics.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ResourcesSettings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourcesSettings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Technics.Properties.ResourcesSettings", typeof(ResourcesSettings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Каталоги.
        /// </summary>
        internal static string Category_Directories {
            get {
                return ResourceManager.GetString("Category.Directories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Формат.
        /// </summary>
        internal static string Category_Format {
            get {
                return ResourceManager.GetString("Category.Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Расположение файла базы данных.
        ///Пустое значение — \AppData\Local\P3tr0viCh\Technics\.
        /// </summary>
        internal static string DirectoryDatabase_Description {
            get {
                return ResourceManager.GetString("DirectoryDatabase.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to База данных.
        /// </summary>
        internal static string DirectoryDatabase_DisplayName {
            get {
                return ResourceManager.GetString("DirectoryDatabase.DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Формат даты и времени.
        /// </summary>
        internal static string Format_FormatDateTime_DisplayName {
            get {
                return ResourceManager.GetString("Format.FormatDateTime.DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Формат пробега.
        /// </summary>
        internal static string Format_FormatMileage_DisplayName {
            get {
                return ResourceManager.GetString("Format.FormatMileage.DisplayName", resourceCulture);
            }
        }
    }
}
