//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Technics.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Technics.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Указанный общий пробег ({0}) меньше или равен уже внесённому в базу данных ({1})..
        /// </summary>
        internal static string ErrorMileageCommonWrong {
            get {
                return ResourceManager.GetString("ErrorMileageCommonWrong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не один из пробегов не указан..
        /// </summary>
        internal static string ErrorMileagesEmpty {
            get {
                return ResourceManager.GetString("ErrorMileagesEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Деталь «{0}» установлена на {1} {2}.
        ///Необходимо указать дату снятия..
        /// </summary>
        internal static string ErrorPartDateInstallLessDateNextInstall {
            get {
                return ResourceManager.GetString("ErrorPartDateInstallLessDateNextInstall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дата установки детали «{0}» меньше даты снятия с {1} ({2})..
        /// </summary>
        internal static string ErrorPartDateInstallLessDateRemove {
            get {
                return ResourceManager.GetString("ErrorPartDateInstallLessDateRemove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Деталь «{0}» установлена на {1} {2}.
        ///Указанная дата снятия больше даты последующей установки..
        /// </summary>
        internal static string ErrorPartDateRemoveGreaterDateNextInstall {
            get {
                return ResourceManager.GetString("ErrorPartDateRemoveGreaterDateNextInstall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Деталь не указана..
        /// </summary>
        internal static string ErrorPartEmpty {
            get {
                return ResourceManager.GetString("ErrorPartEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Деталь «{0}» уже установлена на {1} {2}..
        /// </summary>
        internal static string ErrorPartInUse {
            get {
                return ResourceManager.GetString("ErrorPartInUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Техника не указана..
        /// </summary>
        internal static string ErrorTechEmpty {
            get {
                return ResourceManager.GetString("ErrorTechEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дата снятия меньше даты установки..
        /// </summary>
        internal static string ErrorTechPartDatesWrong {
            get {
                return ResourceManager.GetString("ErrorTechPartDatesWrong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Необходимо указать число..
        /// </summary>
        internal static string ErrorValueNeedDouble {
            get {
                return ResourceManager.GetString("ErrorValueNeedDouble", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Значение должно быть больше нуля..
        /// </summary>
        internal static string ErrorValueNeedGreaterZero {
            get {
                return ResourceManager.GetString("ErrorValueNeedGreaterZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Во время создания базы данных произошла ошибка:
        ///{0}.
        /// </summary>
        internal static string MsgDatabaseCreateFail {
            get {
                return ResourceManager.GetString("MsgDatabaseCreateFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Во время удаления записи из базы данных произошла ошибка:
        ///{0}.
        /// </summary>
        internal static string MsgDatabaseListItemDeleteFail {
            get {
                return ResourceManager.GetString("MsgDatabaseListItemDeleteFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Во время сохранения записи в базу данных произошла ошибка:
        ///{0}.
        /// </summary>
        internal static string MsgDatabaseListItemSaveFail {
            get {
                return ResourceManager.GetString("MsgDatabaseListItemSaveFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Во время обращения к базе данных произошла ошибка:
        ///{0}..
        /// </summary>
        internal static string MsgDatabaseLoadFail {
            get {
                return ResourceManager.GetString("MsgDatabaseLoadFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Удалить «{0}» из базы данных?.
        /// </summary>
        internal static string QuestionFolderDelete {
            get {
                return ResourceManager.GetString("QuestionFolderDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Удалить «{0}» из базы данных?
        ///Содержимое папки будет перемещено в родительскую..
        /// </summary>
        internal static string QuestionFolderDeleteNotEmpty {
            get {
                return ResourceManager.GetString("QuestionFolderDeleteNotEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Удалить «{0}»?.
        /// </summary>
        internal static string QuestionItemDelete {
            get {
                return ResourceManager.GetString("QuestionItemDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Удалить «{0}» из базы данных?
        ///Все значения в связанных записях будут отмечены пустыми..
        /// </summary>
        internal static string QuestionItemLinkedDelete {
            get {
                return ResourceManager.GetString("QuestionItemLinkedDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Удалить «{0}» и ещё {1}?.
        /// </summary>
        internal static string QuestionItemListDelete {
            get {
                return ResourceManager.GetString("QuestionItemListDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Удалить «{0}» и ещё {1} из базы данных?
        ///Все значения в связанных записях будут отмечены пустыми..
        /// </summary>
        internal static string QuestionItemListLinkedDelete {
            get {
                return ResourceManager.GetString("QuestionItemListLinkedDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Удалить «{0}» из базы данных?.
        /// </summary>
        internal static string QuestionMileageDelete {
            get {
                return ResourceManager.GetString("QuestionMileageDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Удалить «{0}» с датой установки {1} из базы данных?.
        /// </summary>
        internal static string QuestionTechPartDelete {
            get {
                return ResourceManager.GetString("QuestionTechPartDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Количество: {0}.
        /// </summary>
        internal static string StatusCount {
            get {
                return ResourceManager.GetString("StatusCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пробеги: {0}.
        /// </summary>
        internal static string StatusMileageCount {
            get {
                return ResourceManager.GetString("StatusMileageCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выделено: {0}.
        /// </summary>
        internal static string StatusSelectedCount {
            get {
                return ResourceManager.GetString("StatusSelectedCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Детали: {0}.
        /// </summary>
        internal static string StatusTechPartCount {
            get {
                return ResourceManager.GetString("StatusTechPartCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Наименование.
        /// </summary>
        internal static string TextLabelText {
            get {
                return ResourceManager.GetString("TextLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дождитесь окончания выполнения текущей операции..
        /// </summary>
        internal static string TextProgramBusy {
            get {
                return ResourceManager.GetString("TextProgramBusy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Техника.
        /// </summary>
        internal static string TextTechAll {
            get {
                return ResourceManager.GetString("TextTechAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Папка.
        /// </summary>
        internal static string TitleFolder {
            get {
                return ResourceManager.GetString("TitleFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Комплектующие.
        /// </summary>
        internal static string TitleListParts {
            get {
                return ResourceManager.GetString("TitleListParts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Техника.
        /// </summary>
        internal static string TitleListTechs {
            get {
                return ResourceManager.GetString("TitleListTechs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Учёт и обслуживание техники {0}.
        /// </summary>
        internal static string TitleMain {
            get {
                return ResourceManager.GetString("TitleMain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Деталь.
        /// </summary>
        internal static string TitlePart {
            get {
                return ResourceManager.GetString("TitlePart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Техника.
        /// </summary>
        internal static string TitleTech {
            get {
                return ResourceManager.GetString("TitleTech", resourceCulture);
            }
        }
    }
}
