//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Technics.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Technics.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Во время создания базы данных произошла ошибка:
        ///{0}.
        /// </summary>
        internal static string MsgDatabaseCreateFail {
            get {
                return ResourceManager.GetString("MsgDatabaseCreateFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Во время удаления записи из базы данных произошла ошибка:
        ///{0}.
        /// </summary>
        internal static string MsgDatabaseListItemDeleteFail {
            get {
                return ResourceManager.GetString("MsgDatabaseListItemDeleteFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Во время сохранения записи в базу данных произошла ошибка:
        ///{0}.
        /// </summary>
        internal static string MsgDatabaseListItemSaveFail {
            get {
                return ResourceManager.GetString("MsgDatabaseListItemSaveFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Во время обращения к базе данных произошла ошибка:
        ///{0}..
        /// </summary>
        internal static string MsgDatabaseLoadFail {
            get {
                return ResourceManager.GetString("MsgDatabaseLoadFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Удалить «{0}» из базы данных?
        ///Содержимое папки будет перемещено в родительскую..
        /// </summary>
        internal static string QuestionDeleteListItem {
            get {
                return ResourceManager.GetString("QuestionDeleteListItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Удалить «{0}» из базы данных?.
        /// </summary>
        internal static string QuestionDeleteListItemEmpty {
            get {
                return ResourceManager.GetString("QuestionDeleteListItemEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Техника.
        /// </summary>
        internal static string TextTechAll {
            get {
                return ResourceManager.GetString("TextTechAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Учёт и обслуживание техники {0}.
        /// </summary>
        internal static string TitleMain {
            get {
                return ResourceManager.GetString("TitleMain", resourceCulture);
            }
        }
    }
}
